'use client';

import { Product } from '@/components/ui/Product';

const globalDiscount = 30;

const formatPrice = (value: number): string => {
  return value.toLocaleString('ru-RU') + ' ₽';
};

const calculateProductDetails = (
  area: number,
  basePrice: number,
  discount: number
) => {
  const capacity = Math.floor(area * 0.67);
  const discountedPrice = basePrice * (1 - discount / 100);
  return {
    capacity: `${capacity} человек`,
    oldPrice: formatPrice(basePrice),
    discount: `-${discount}%`,
    price: `от ${formatPrice(discountedPrice)}`,
  };
};

const mockProducts: Product[] = (
  [
    {
      id: 'zont-dlya-kafe-desert-2h2',
      title: 'Зонт для кафе Desert 2х2',
      images: ['/zont1.webp', '/zont2.webp', '/zont4.webp'],
      size: '2х2м',
      area: 4,
      availability: "да",
      basePrice: 380000,
      discountPercentage: 50,
      shape: "Квадрат"
    },
    {
      id: 'glemping-diametr-10-m',
      title: 'Глэмпинг диаметр 10м',
      images: ['/glemping2.webp', '/glemping1.webp', '/glemping3.webp'],
      size: '10м',
      area: 78,
      availability: "да",
      basePrice: 1143000,
      discountPercentage: 20,
      price: "",
      shape: "Круг"
    },
    {
      id: 'shatyor-zvezda-16-h-10',
      title: 'Шатёр Звезда 16 х 10',
      images: ['/zvezda.webp', '/zvezda1.webp', '/zvezda2.webp'],
      size: '16 x 10м',
      area: 171,
      availability: "да",
      basePrice: 309000,
      discountPercentage: 10,
      price: "",
      shape: "Звезда"
    },
    {
      id: 'shestigrannyy-shatyor-rimini-diametr-6-m',
      title: 'Шестигранный шатёр Римини (Диаметр 6 м)',
      images: ['/shesteg1.webp', '/shesteg2.webp', '/shesteg5.webp'],
      size: '6м',
      area: 28,
      availability: "да",
      basePrice: 351000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'arochnyy-shatyor-10h10-100-m2v',
      title: 'Арочный шатёр 10х10 — 100 м2(V)',
      images: ['/1(1).webp' , '/2.webp' , '/Образмер (1).webp'],
      size: '10х10м',
      area: 100,
      availability: "да",
      basePrice: 657000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-6h6-36-m2',
      title: 'Арочный шатёр 6х6 — 36 м2',
      images: ['/1(2).webp' , '/3(1).webp' , "/Образмер.jpg"],
      size: '6х6м',
      area: 36,
      availability: "да",
      basePrice: 342000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'kupolnyy-shater-diametr-10-m',
      title: 'Купольный шатер диаметр 10 м',
      images: ['/kopalnytent1.webp' , '/kopalnytent2.webp' , '/kopalnytent3.webp'],
      size: '10x10м',
      area: 79,
      availability: "да",
      basePrice: 90000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'naduvnoy-shater-8h8',
      title: 'Надувной шатер 8х8',
      images: ['/nadovne1.webp', '/nadovne2.webp', '/nadovne3.webp'],
      size: '8х8м',
      area: 64,
      availability: "да",
      basePrice: 913000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'klassicheskiy-shatyor-10h10',
      title: 'Классический шатёр 10х10',
      images: ['/classical1.webp', '/classical2.webp', '/classical3.webp'],
      size: '10х10м',
      area: 100,
      availability: "да",
      basePrice: 999000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'klassicheskiy-shatyor-15h20',
      title: 'Классический шатёр 15х20',
      images: ['/pryam1.webp', '/pryam2.webp', '/pryam3.webp'],
      size: '15х20м',
      area: 64,
      availability: "да",
      basePrice: 2175000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-20h20-400-m2',
      title: 'Арочный шатёр 20х20 — 400 м2',
      images: ['/20x20,1.webp', '/20x20,2.webp', '/20x20,3.webp'],
      size: '20х20м',
      area: 400,
      availability: "да",
      basePrice: 2206000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-10x15-m',
      title: 'Шатёр для мероприятий 10x15 м',
      images: ['/classical1.webp', '/classical2.webp', '/classical3.webp'],
      size: '10х15м',
      area: 150,
      availability: "да",
      basePrice: 1293000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shestigrannyy-shatyor-london-diametr-8-m',
      title: 'Шестигранный шатёр Лондон (Диаметр 8 м)',
      images: ['/shesteg1.webp', '/shesteg2.webp', '/shesteg6.webp'],
      size: '8м',
      area: 50,
      availability: "да",
      basePrice: 640000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shatyor-dlya-vystavok-10h30',
      title: 'Шатёр для выставок 10х30',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'],
      size: '10х30м',
      area: 300,
      availability: "да",
      basePrice: 2235000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-pagoda-standart-6h6',
      title: 'Шатёр Пагода Стандарт 6х6',
      images: ['/pagda4.webp' , '/pagda5.webp' , '/pagdan.webp'],
      size: '6х6м',
      area: 36,
      availability: "да",
      basePrice: 302000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-pagoda-london-3h3',
      title: 'Шатёр Пагода Лондон 3х3',
      images: ['/pagda4.webp' , '/pagda5.webp' , '/pagda6.jpg'],
      size: '3х3м',
      area: 9,
      availability: "да",
      basePrice: 176000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-15h30',
      title: 'Шатёр для мероприятий 15х30',
      images: ['/classical1.webp', '/classical2.webp', '/classical4.webp'],
      size: '15х30м',
      area: 450,
      availability: "да",
      basePrice: 2972000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
   {
      id: 'shatry-pagoda-s-ostroy-kryshey-standart-5h5',
      title: 'Шатры Пагода с острой крышей Стандарт 5х5',
      images: ['/pagda4.webp' , '/pagda5.webp' , '/pagdan1.webp'],
      size: '5х5м',
      area: 9,
      availability: "да",
      basePrice: 225000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-10h10-100-m2v',
      title: 'Арочный шатёр 10х10 — 100 м2',
      images: ['/1(1).webp' , '/2.webp' , '/Образмер (1).webp'],
      size: '10х10м',
      area: 100,
      availability: "да",
      basePrice: 657000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-5h5-25-m2',
      title: 'Арочный шатёр 5х5 — 25 м2',
      images: ['/small1.webp' , '/small2.webp' , '/small3.webp'],
      size: '5х5м',
      area: 25,
      availability: "да",
      basePrice: 197000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-8h8-64m2v',
      title: 'Арочный шатёр 8х8 — 64м2',
      images: ['/1(2).webp' , '/3(1).webp' , "/8x8.jpg"],
      size: '8х8м',
      area: 64,
      availability: "да",
      basePrice: 566000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-pagoda-london-10h10',
      title: 'Шатёр Пагода Лондон 10х10',
      images: ['/pagda1.webp' , '/pagda2.webp' , '/pagda3.webp'],
      size: '10х10м',
      area: 100,
      availability: "да",
      basePrice: 999000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'bystrosbornye-shatry-transformery-prof-3h3',
      title: 'Быстросборные шатры трансформеры Prof 3х3',
      images: ['/pagda4.webp' , '/pagda5.webp' , '/pagda6.jpg'],
      size: '3х3м',
      area: 9,
      availability: "да",
      basePrice: 79000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-12h12-144-m2',
      title: 'Арочный шатёр 12х12 — 144 м2',
      images: ['/12x12,1.webp' , '/12x12,2.webp' , '/hexag1.webp'],
      size: '12х12м',
      area: 144,
      availability: "да",
      basePrice: 976000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'bystrosbornye-shatry-transformery-prof-3h6',
      title: 'Быстросборные шатры трансформеры Prof 3х6',
      images: ['/mobilny4.webp' , '/mobilny5.webp' , '/mobilny6.webp'],
      size: '3х6м',
      area: 18,
      availability: "да",
      basePrice: 123000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'klassicheskiy-shatyor-15h30',
      title: 'Классический шатёр 15х30',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'],
      size: '15х30м',
      area: 450,
      availability: "да",
      basePrice: 2972000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'mobilnye-shatry-transformery-prof-4h8',
      title: 'Мобильные шатры-трансформеры Prof 4х8',
      images: ['/mobilny4.webp' , '/mobilny5.webp' , '/mobilny6.webp'],
      size: '4х8м',
      area: 32,
      availability: "да",
      basePrice: 142000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-10h10',
      title: 'Шатёр для выставок 10х10',
      images: ['/classical1.webp', '/classical2.webp', '/classical4.webp'],
      size: '10х10м',
      area: 100,
      availability: "да",
      basePrice: 999000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-20h17-260-m2',
      title: 'Арочный шатёр 20х17 — 260 м2',
      images: ['/20x17,1.webp', '/20x17,2.webp', '/20x17,3.webp'],
      size: '10х10м',
      area: 260,
      availability: "да",
      basePrice: 1407000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-6h3-18-m2',
      title: 'Арочный шатёр 6х3 — 18 м2',
      images: ['/6x3,1.webp', '/6x3,2.webp', '/6x3,3.webp'],
      size: '6х3м',
      area: 18,
      availability: "да",
      basePrice: 189000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-5h5-25-m2v',
      title: 'Арочный шатёр 5х5 — 25 м2',
      images: ['/small1.webp' , '/small2.webp' , '/small3.webp'],
      size: '5х5м',
      area: 25,
      availability: "да",
      basePrice: 163000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-35h35-1225-m2',
      title: 'Арочный шатёр 3,5х3,5 — 12,25 м2',
      images: ['/small1.webp' , '/small2.webp' , '/small3.webp'],
      size: '3.5х3.5м',
      area: 12.25,
      availability: "да",
      basePrice: 150000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-6h5-30-m2',
      title: 'Арочный шатёр 6х5 — 30 м2',
      images: ['/6x3,1.webp', '/6x3,2.webp', '/6x3,3.webp'],
      size: '6х5м',
      area: 30,
      availability: "да",
      basePrice: 229000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-8h4-32-m2',
      title: 'Арочный шатёр 8х4 — 32 м2',
      images: ['/6x3,1.webp', '/6x3,2.webp', '/6x3,3.webp'],
      size: '8х4м',
      area: 32,
      availability: "да",
      basePrice: 229000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-35h35-1225-m2v',
      title: 'Арочный шатёр 3.5х3.5 — 12,25 м2',
      images: ['/small1.webp' , '/small2.webp' , '/small3.webp'],
      size: '3.5х3.5м',
      area: 12.25,
      availability: "да",
      basePrice: 157000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-10h3-30-m2',
      title: 'Арочный шатёр 10х3 — 30 м2',
      images: ['/6x3,1.webp', '/6x3,2.webp', '/6x3,3.webp'],
      size: '10х3м',
      area: 30,
      availability: "да",
      basePrice: 229000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-8h3-24-m2',
      title: 'Арочный шатёр 8х3 — 24 м2',
      images: ['/6x3,1.webp', '/6x3,2.webp', '/6x3,3.webp'],
      size: '8х3м',
      area: 24,
      availability: "да",
      basePrice: 172000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-10h10-100-m2',
      title: 'Арочный шатёр 10х10 — 100 м2',
      images: ['/1(2).webp' , '/3(1).webp' , "/Образмер.jpg"],
      size: '10х10м',
      area: 100,
      availability: "да",
      basePrice: 596000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-8h8-64-m2',
      title: 'Арочный шатёр 8х8 — 64 м2',
      images: ['/1(2).webp' , '/3(1).webp' , "/Образмер.jpg"],
      size: '8х8м',
      area: 64,
      availability: "да",
      basePrice: 524000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shestigrannyy-shatyor-rimini-diametr-12-m',
      title: 'Шестигранный шатёр Римини (Диаметр 12 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg3.webp'],
      size: '12м',
      area: 113,
      availability: "да",
      basePrice: 396000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shestigrannyy-shatyor-rimini-diametr-15-m',
      title: 'Шестигранный шатёр Римини (Диаметр 15 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg4.webp'],
      size: '15м',
      area: 176,
      availability: "да",
      basePrice: 2528000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shestigrannyy-shatyor-rimini-diametr-10-m',
      title: 'Шестигранный шатёр Римини (Диаметр 10 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg3.webp'],
      size: '10м',
      area: 78,
      availability: "да",
      basePrice: 990000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shestigrannyy-shatyor-standart-diametr-15-m',
      title: 'Шестигранный шатёр Стандарт (Диаметр 15 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg4.webp'],
      size: '15м',
      area: 176,
      availability: "да",
      basePrice: 2022000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shestigrannyy-shatyor-rimini-diametr-8-m',
      title: 'Шестигранный шатёр Римини (Диаметр 8 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg5.webp'],
      size: '8м',
      area: 50,
      availability: "да",
      basePrice: 640000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shestigrannyy-shatyor-standart-diametr-12-m',
      title: 'Шестигранный шатёр Стандарт (Диаметр 12 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg3.webp'],
      size: '12м',
      area: 113,
      availability: "да",
      basePrice: 1133000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shestigrannyy-shatyor-standart-diametr-10-m',
      title: 'Шестигранный шатёр Стандарт (Диаметр 10 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg3.webp'],
      size: '10м',
      area: 78,
      availability: "да",
      basePrice: 792000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shestigrannyy-shatyor-london-diametr-12-m',
      title: 'Шестигранный шатёр Лондон (Диаметр 12 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg3.webp'],
      size: '12м',
      area: 113,
      availability: "да",
      basePrice: 1416000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shestigrannyy-shatyor-london-diametr-10-m',
      title: 'Шестигранный шатёр Лондон (Диаметр 10 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg3.webp'],
      size: '10м',
      area: 78,
      availability: "да",
      basePrice: 990000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shestigrannyy-shatyor-london-diametr-15-m',
      title: 'Шестигранный шатёр Лондон (Диаметр 15 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg4.webp'],
      size: '15м',
      area: 176,
      availability: "да",
      basePrice: 2528000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shestigrannyy-shatyor-london-diametr-6-m',
      title: 'Шестигранный шатёр Лондон (Диаметр 6 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg5.webp'],
      size: '6м',
      area: 28,
      availability: "да",
      basePrice: 351000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shestigrannyy-shatyor-standart-diametr-6-m',
      title: 'Шестигранный шатёр Стандарт (Диаметр 6 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg5.webp'],
      size: '6м',
      area: 28,
      availability: "да",
      basePrice: 281000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'shestigrannyy-shatyor-standart-diametr-8-m',
      title: 'Шестигранный шатёр Стандарт (Диаметр 8 м)',
      images: ['/shesteg1.webp' , '/shesteg2.webp' , '/shesteg5.webp'],
      size: '8м',
      area: 50,
      availability: "да",
      basePrice: 512000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Шестигранник"
    },
    {
      id: 'sfericheskiy-shatyor-26-m',
      title: 'Сферический шатёр 26 м',
      images: ['/spher7.webp' , '/spher8.webp' , '/spher9.webp'],
      size: '26м',
      area: 26,
      availability: "да",
      basePrice: 512000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Круг"
    },
    {
      id: 'klassicheskiy-shatyor-15h40',
      title: 'Классический шатёр 15х40',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '15х40м',
      area: 600,
      availability: "да",
      basePrice: 3735000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'klassicheskiy-shatyor-10h30',
      title: 'Классический шатёр 10х30',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '10х30м',
      area: 300,
      availability: "да",
      basePrice: 2235000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'klassicheskiy-shatyor-15h15',
      title: 'Классический шатёр 15х15',
      images: ['/classical1.webp', '/classical2.webp', '/classical4.webp'],
      size: '15х15м',
      area: 225,
      availability: "да",
      basePrice: 1788000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'klassicheskiy-shatyor-10h40',
      title: 'Классический шатёр 10х40',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '10х40м',
      area: 400,
      availability: "да",
      basePrice: 2846000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-pagoda-london-8h8',
      title: 'Шатёр Пагода Лондон 8х8',
      images: ['/pagda1.webp' , '/pagda2.webp' , '/pagda3.webp'],
      size: '8х8м',
      area: 64,
      availability: "да",
      basePrice: 598000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatry-pagoda-s-ostroy-kryshey-london-4h4',
      title: 'Шатры Пагода с острой крышей Лондон 4х4',
      images: ['/pagda4.webp' , '/pagda5.webp' , '/pagda6.jpg'],
      size: '4х4м',
      area: 16,
      availability: "да",
      basePrice: 211000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-zvezda-diametr-6-m',
      title: 'Шатёр Звезда (Диаметр 6 м)',
      images: ['/zvezda.webp', '/zvezda1.webp', '/zvezda2.webp'],
      size: '6м',
      area: 28.26,
      availability: "да",
      basePrice: 163000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Звезда"
    },
    {
      id: 'klassicheskiy-shatyor-20h40',
      title: 'Классический шатёр 20х40',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '20х40м',
      area: 800,
      availability: "да",
      basePrice: 7370000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'mobilnyy-shatyor-hard-prof-3h3',
      title: 'Мобильный шатёр Hard Prof 3х3',
      images: ['/mobilny1.webp' , '/mobilny2.webp' , '/mobilny3.webp'],
      size: '3х3м',
      area: 9,
      availability: "да",
      basePrice: 79000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'mobilnyy-shatyor-hard-prof-3h6',
      title: 'Мобильный шатёр Hard Prof 3х6',
      images: ['/mobilny4.webp' , '/mobilny5.webp' , '/mobilny6.webp'],
      size: '3х6м',
      area: 18,
      availability: "да",
      basePrice: 123000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'mobilnyy-shatyor-hard-prof-3h45',
      title: 'Мобильный шатёр Hard Prof 3х4.5',
      images: ['/mobilny4.webp' , '/mobilny5.webp' , '/mobilny6.webp'],
      size: '3х4.5м',
      area: 13.5,
      availability: "да",
      basePrice: 90000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'klassicheskiy-shatyor-25h40',
      title: 'Классический шатёр 25х40',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '25х40м',
      area: 1000,
      availability: "да",
      basePrice: 7645000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'klassicheskiy-shatyor-20h35',
      title: 'Классический шатёр 20х35',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '20х35м',
      area: 700,
      availability: "да",
      basePrice: 6593000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatry-pagoda-s-ostroy-kryshey-standart-3h3',
      title: 'Шатры Пагода с острой крышей Стандарт 3х3',
      images: ['/pagda4.webp' , '/pagda5.webp' , '/pagda6.jpg'],
      size: '3х3м',
      area: 9,
      availability: "да",
      basePrice: 158000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-zvezda-diametr-14-m',
      title: 'Шатёр Звезда (Диаметр 14 м)',
      images: ['/zvezda.webp', '/zvezda1.webp', '/zvezda2.webp'],
      size: '14м',
      area: 153.86,
      availability: "да",
      basePrice: 223000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Звезда"
    },
    {
      id: 'klassicheskiy-shatyor-25h30',
      title: 'Классический шатёр 25х30',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '25х30м',
      area: 750,
      availability: "да",
      basePrice: 6046000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-15h13-163-m2',
      title: 'Арочный шатёр 15х13 — 163 м2',
      images: ['/1.webp' , '/3.webp' , '/Образмер.webp'],
      size: '15х13м',
      area: 163,
      availability: "да",
      basePrice: 1040000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'bystrosbornye-shatry-transformery-prof-3h45',
      title: 'Быстросборные шатры трансформеры Prof 3х4.5',
      images: ['/mobilny1.webp' , '/mobilny2.webp' , '/mobilny3.webp'],
      size: '3х4.5м',
      area: 13.5,
      availability: "да",
      basePrice: 90000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-24h16-384-m2',
      title: 'Арочный шатёр 24х16 — 384 м2',
      images: ['/1.webp' , '/3.webp' , '/Образмер.webp'],
      size: '24х16м',
      area: 384,
      availability: "да",
      basePrice: 2573000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-zvezda-22-h-14',
      title: 'Шатёр Звезда 22 х 14',
      images: ['/zvezda.webp', '/zvezda1.webp', '/zvezda2.webp'],
      size: '22х14м',
      area: 302.62,
      availability: "да",
      basePrice: 1475000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Звезда"
    },
    {
      id: 'arochnyy-shatyor-30h20-600-m2',
      title: 'Арочный шатёр 30х20 — 600 м2',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '30х20м',
      area: 600,
      availability: "да",
      basePrice: 4029000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-zvezda-diametr-12-m',
      title: 'Шатёр Звезда (Диаметр 12 м)',
      images: ['/zvezda.webp', '/zvezda1.webp', '/zvezda2.webp'],
      size: '12м',
      area: 113.04,
      availability: "да",
      basePrice: 223000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Звезда"
    },
    {
      id: 'mobilnye-shatry-transformery-prof-4h4',
      title: 'Мобильные шатры-трансформеры Prof 4х4',
      images: ['/mobilny1.webp' , '/mobilny2.webp' , '/mobilny3.webp'],
      size: '4х4м',
      area: 16,
      availability: "да",
      basePrice: 100000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-zvezda-19-h-12',
      title: 'Шатёр Звезда 19 х 12',
      images: ['/zvezda.webp', '/zvezda1.webp', '/zvezda2.webp'],
      size: '19х12м',
      area: 231.11,
      availability: "да",
      basePrice: 906000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Звезда"
    },
    {
      id: 'mobilnye-shatry-transformery-prof-4h6',
      title: 'Мобильные шатры-трансформеры Prof 4х6',
      images: ['/mobilny4.webp' , '/mobilny5.webp' , '/mobilny6.webp'],
      size: '4х6м',
      area: 24,
      availability: "да",
      basePrice: 115000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-21h15-287-m2',
      title: 'Арочный шатёр 21х15 — 287 м2',
      images: ['/1(3).webp' , '/3(oct).webp' , '/4.webp'],
      size: '21х15м',
      area: 287,
      availability: "да",
      basePrice: 1792000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-21x19-m',
      title: 'Арочный шатёр 21x19 м',
      images: ['/1(3).webp' , '/3(oct).webp' , '/4.webp'],
      size: '21х19м',
      area: 305,
      availability: "да",
      basePrice: 2156000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'mobilnyy-shatyor-slim-prof-4h4',
      title: 'Мобильный шатёр Slim Prof 4х4',
      images: ['/mobilny7.webp' , '/mobilny8.webp' , '/mobilny9.webp'],
      size: '4х4м',
      area: 16,
      availability: "да",
      basePrice: 100000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'mobilnyy-shatyor-slim-prof-3h45',
      title: 'Мобильный шатёр Slim Prof 3х4.5',
      images: ['/mobilny1.webp' , '/mobilny2.webp' , '/mobilny3.webp'],
      size: '3х4.5м',
      area: 13.5,
      availability: "да",
      basePrice: 90000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-12h10-94-m2',
      title: 'Арочный шатёр 12х10 — 94 м2',
      images: ['/1.webp' , '/3.webp' , '/Образмер.webp'],
      size: '12х10м',
      area: 94,
      availability: "да",
      basePrice: 986000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-zvezda-diametr-10-m',
      title: 'Шатёр Звезда (Диаметр 10 м)',
      images: ['/zvezda.webp', '/zvezda1.webp', '/zvezda2.webp'],
      size: '10м',
      area: 78.5,
      availability: "да",
      basePrice: 240000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Звезда"
    },
    {
      id: 'mobilnyy-shatyor-slim-prof-3h3',
      title: 'Мобильный шатёр Slim Prof 3х3',
      images: ['/mobilny1.webp' , '/mobilny2.webp' , '/mobilny3.webp'],
      size: '3х3м',
      area: 9,
      availability: "да",
      basePrice: 79000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'mobilnyy-shatyor-slim-prof-3h6',
      title: 'Мобильный шатёр Slim Prof 3х6',
      images: ['/mobilny4.webp' , '/mobilny5.webp' , '/mobilny6.webp'],
      size: '3х6м',
      area: 18,
      availability: "да",
      basePrice: 123000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-pagoda-london-6h6',
      title: 'Шатёр Пагода Лондон 6х6',
      images: ['/pagda1.webp' , '/pagda2.webp' , '/pagda3.webp'],
      size: '6х6м',
      area: 36,
      availability: "да",
      basePrice: 329000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'klassicheskiy-shatyor-25h25',
      title: 'Классический шатёр 25х25',
      images: ['/25x25,1.webp' , '/25x25,2.webp' , '/25x25,3.webp'],
      size: '25х25м',
      area: 625,
      availability: "да",
      basePrice: 5260000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-zvezda-diametr-8-m',
      title: 'Шатёр Звезда (Диаметр 8 м)',
      images: ['/zvezda.webp', '/zvezda1.webp', '/zvezda2.webp'],
      size: '8м',
      area: 50.24,
      availability: "да",
      basePrice: 163000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Звезда"
    },
    {
      id: 'shatyor-zvezda-14-h-9',
      title: 'Шатёр Звезда 14 х 9',
      images: ['/zvezda.webp', '/zvezda1.webp', '/zvezda2.webp'],
      size: '14x9м',
      area: 118.07,
      availability: "да",
      basePrice: 240000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Звезда"
    },
    {
      id: 'shatyor-pagoda-standart-8h8',
      title: 'Шатёр Пагода Стандарт 8х8',
      images: ['/pagda1.webp' , '/pagda2.webp' , '/pagda3.webp'],
      size: '8x8м',
      area: 64,
      availability: "да",
      basePrice: 544000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-pagoda-london-5h5',
      title: 'Шатёр Пагода Лондон 5х5',
      images: ['/pagda4.webp' , '/pagda5.webp' , '/pagda6.jpg'],
      size: '5x5м',
      area: 25,
      availability: "да",
      basePrice: 244000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-25h20-500-m2',
      title: 'Арочный шатёр 25х20 — 500 м2',
      images: ['/1(3).webp' , '/3(oct).webp' , '/4.webp'],
      size: '25х20м',
      area: 500,
      availability: "да",
      basePrice: 2827000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-zvezda-diametr-16-m',
      title: 'Шатёр Звезда (Диаметр 16 м)',
      images: ['/zvezda.webp', '/zvezda1.webp', '/zvezda2.webp'],
      size: '16м',
      area: 200.96,
      availability: "да",
      basePrice: 330000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Звезда"
    },
    {
      id: 'arochnyy-shatyor-18h15-241-m2',
      title: 'Арочный шатёр 18х15 — 241 м2',
      images: ['/1(3).webp' , '/3(oct).webp' , '/4.webp'],
      size: '18х15м',
      area: 241,
      availability: "да",
      basePrice: 1371000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-zvezda-16-h-10',
      title: 'Шатёр Звезда 16 х 10',
      images: ['/zvezda.webp', '/zvezda1.webp', '/zvezda2.webp'],
      size: '16x10м',
      area: 170.56,
      availability: "да",
      basePrice: 309000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Звезда"
    },
    {
      id: 'shatyor-pagoda-standart-10h10',
      title: 'Шатёр Пагода Стандарт 10х10',
      images: ['/pagda1.webp' , '/pagda2.webp' , '/pagda3.webp'],
      size: '10x10м',
      area: 100,
      availability: "да",
      basePrice: 960000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'mobilnyy-shatyor-hard-prof-4h4',
      title: 'Мобильный шатёр Hard Prof 4х4',
      images: ['/mobilny7.webp' , '/mobilny8.webp' , '/mobilny9.webp'],
      size: '4x4м',
      area: 16,
      availability: "да",
      basePrice: 100000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'mobilnyy-shatyor-hard-prof-4h6',
      title: 'Мобильный шатёр Hard Prof 4х6',
      images: ['/mobilny4.webp' , '/mobilny5.webp' , '/mobilny6.webp'],
      size: '4x6м',
      area: 24,
      availability: "да",
      basePrice: 115000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'mobilnyy-shatyor-hard-prof-4h8',
      title: 'Мобильный шатёр Hard Prof 4х8',
      images: ['/mobilny4.webp' , '/mobilny5.webp' , '/mobilny6.webp'],
      size: '4x8м',
      area: 32,
      availability: "да",
      basePrice: 142000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'mobilnyy-shatyor-slim-prof-4h6',
      title: 'Мобильный шатёр Slim Prof 4х6',
      images: ['/mobilny4.webp' , '/mobilny5.webp' , '/mobilny6.webp'],
      size: '4x6м',
      area: 24,
      availability: "да",
      basePrice: 115000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'mobilnyy-shatyor-slim-prof-4h8',
      title: 'Мобильный шатёр Slim Prof 4х8',
      images: ['/mobilny4.webp' , '/mobilny5.webp' , '/mobilny6.webp'],
      size: '4x8м',
      area: 32,
      availability: "да",
      basePrice: 142000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-10h35',
      title: 'Шатёр для мероприятий 10х35',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '10x35м',
      area: 350,
      availability: "да",
      basePrice: 2527000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-10h30',
      title: 'Шатёр для мероприятий 10х30',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '10x30м',
      area: 300,
      availability: "да",
      basePrice: 2235000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-15h25',
      title: 'Шатёр для мероприятий 15х25',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '15x25м',
      area: 375,
      availability: "да",
      basePrice: 2585000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-10h40',
      title: 'Шатёр для мероприятий 10х40',
      images: ['/10x40,1.webp', '/10x40,2.webp', '/10x40,3.webp'], 
      size: '10x40м',
      area: 400,
      availability: "да",
      basePrice: 2846000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-10x10-m',
      title: 'Шатёр для мероприятий 10x10 м',
      images: ['/10x10,1.webp' , '/10x10,2.webp' , '/10x10,3.webp'],
      size: '10x10м',
      area: 100,
      availability: "да",
      basePrice: 999000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-15h40',
      title: 'Шатёр для мероприятий 15х40',
      images: ['/10x40,1.webp', '/10x40,2.webp', '/10x40,3.webp'], 
      size: '15x40м',
      area: 600,
      availability: "да",
      basePrice: 3735000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-10h25',
      title: 'Шатёр для мероприятий 10х25',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '10x25м',
      area: 250,
      availability: "да",
      basePrice: 1923000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-15h20',
      title: 'Шатёр для мероприятий 15х20',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '15x20м',
      area: 300,
      availability: "да",
      basePrice: 2175000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-15h35',
      title: 'Шатёр для мероприятий 15х35',
      images: ['/10x40,1.webp', '/10x40,2.webp', '/10x40,3.webp'], 
      size: '15x35м',
      area: 525,
      availability: "да",
      basePrice: 3356000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-10h20-m',
      title: 'Шатёр для мероприятий 10х20 мb',
      images: ['/10x40,1.webp', '/10x40,2.webp', '/10x40,3.webp'], 
      size: '10x20м',
      area: 200,
      availability: "да",
      basePrice: 1596000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-15h15',
      title: 'Шатёр для мероприятий 15х15',
      images: ['/10x10,1.webp' , '/10x10,2.webp' , '/10x10,3.webp'],
      size: '15x15м',
      area: 225,
      availability: "да",
      basePrice: 1788000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-20h25',
      title: 'Шатёр для мероприятий 20х25',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '20x25м',
      area: 500,
      availability: "да",
      basePrice: 5070000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-20h20',
      title: 'Шатёр для мероприятий 20х20',
      images: ['/20x20,4.webp' , '/20x20,5.webp' , '/20x20,6.webp'],
      size: '20x20м',
      area: 400,
      availability: "да",
      basePrice: 4239000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-dlya-vystavok-10h25',
      title: 'Шатёр для выставок 10х25',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '20x25м',
      area: 250,
      availability: "да",
      basePrice: 1923000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-15h30',
      title: 'Шатёр для выставок 15х30',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '15x30м',
      area: 450,
      availability: "да",
      basePrice: 1755000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-15h15',
      title: 'Шатёр для выставок 15х15',
      images: ['/10x10,1.webp' , '/10x10,2.webp' , '/10x10,3.webp'],
      size: '15x15м',
      area: 225,
      availability: "да",
      basePrice: 1788000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-dlya-vystavok-10h40',
      title: 'Шатёр для выставок 10х40',
      images: ['/10x40,1.webp', '/10x40,2.webp', '/10x40,3.webp'], 
      size: '10x40м',
      area: 400,
      availability: "да",
      basePrice: 2846000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-10h20',
      title: 'Шатёр для выставок 10х20',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '10x20м',
      area: 200,
      availability: "да",
      basePrice: 1596000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-15h35',
      title: 'Шатёр для выставок 15х35',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '15x35м',
      area: 525,
      availability: "да",
      basePrice: 3356000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-10h35',
      title: 'Шатёр для выставок 10х35',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '10x35м',
      area: 350,
      availability: "да",
      basePrice: 2527000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-10h15',
      title: 'Шатёр для выставок 10х15',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '10x15м',
      area: 150,
      availability: "да",
      basePrice: 1293000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-20h20',
      title: 'Шатёр для выставок 20х20',
      images: ['/20x20,4.webp' , '/20x20,5.webp' , '/20x20,6.webp'],
      size: '20x20м',
      area: 400,
      availability: "да",
      basePrice: 4239000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-dlya-vystavok-15h40',
      title: 'Шатёр для выставок 15х40',
      images: ['/10x40,1.webp', '/10x40,2.webp', '/10x40,3.webp'], 
      size: '15x40м',
      area: 600,
      availability: "да",
      basePrice: 3735000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-20h25',
      title: 'Шатёр для выставок 20х25',
      images: ['/10x30,1.webp', '/10x30,2.webp', '/10x30,3.webp'], 
      size: '20x25м',
      area: 500,
      availability: "да",
      basePrice: 5070000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-15h20',
      title: 'Шатёр для выставок 15х20',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '15x20м',
      area: 300,
      availability: "да",
      basePrice: 2175000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-25h30',
      title: 'Шатёр для мероприятий 25х30',
      images: ['/10x40,1.webp', '/10x40,2.webp', '/10x40,3.webp'], 
      size: '25x30м',
      area: 750,
      availability: "да",
      basePrice: 6046000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-25h40',
      title: 'Шатёр для выставок 25х40',
      images: ['/10x40,1.webp', '/10x40,2.webp', '/10x40,3.webp'], 
      size: '25x40м',
      area: 1000,
      availability: "да",
      basePrice: 7645000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-25h30',
      title: 'Шатёр для выставок 25х30',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '25x30м',
      area: 750,
      availability: "да",
      basePrice: 6046000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-25h40',
      title: 'Шатёр для мероприятий 25х40',
      images: ['/10x40,1.webp', '/10x40,2.webp', '/10x40,3.webp'], 
      size: '25x40м',
      area: 1000,
      availability: "да",
      basePrice: 7645000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-25h35',
      title: 'Шатёр для выставок 25х35',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '25x35м',
      area: 875,
      availability: "да",
      basePrice: 6858000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-25h25',
      title: 'Шатёр для мероприятий 25х25',
      images: ['/20x20,4.webp' , '/20x20,5.webp' , '/20x20,6.webp'],
      size: '25x25м',
      area: 625,
      availability: "да",
      basePrice: 5260000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-25h35',
      title: 'Шатёр для мероприятий 25х35',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '25x35м',
      area: 875,
      availability: "да",
      basePrice: 6858000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-20h35',
      title: 'Шатёр для мероприятий 20х35',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '20x35м',
      area: 700,
      availability: "да",
      basePrice: 6593000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-16h16-256-m2-b',
      title: 'Арочный шатёр 16х16 — 256 м2 (B)',
      images: ['/1(3).webp' , '/3(oct).webp' , '/4.webp'],
      size: '16x16м',
      area: 256,
      availability: "да",
      basePrice: 6593000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-27h20-460-m2',
      title: 'Арочный шатёр 27х20 — 460 м2',
      images: ['/1(3).webp' , '/3(oct).webp' , '/4.webp'],
      size: '27x20м',
      area: 460,
      availability: "да",
      basePrice: 2970000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-22h20-360-m2',
      title: 'Арочный шатёр 22х20 — 360 м2',
      images: ['/1(3).webp' , '/3(oct).webp' , '/4.webp'],
      size: '22x20м',
      area: 360,
      availability: "да",
      basePrice: 2120000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-26h24-460-m2',
      title: 'Арочный шатёр 26х24 — 460 м2',
      images: ['/1(3).webp' , '/3(oct).webp' , '/4.webp'],
      size: '26x24м',
      area: 460,
      availability: "да",
      basePrice: 3392000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'arochnyy-shatyor-16h16-256-m2',
      title: 'Арочный шатёр 16х16 — 256 м2',
      images: ['/1(3).webp' , '/3(oct).webp' , '/4.webp'],
      size: '16x16м',
      area: 256,
      availability: "да",
      basePrice: 1407000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    {
      id: 'arochnyy-shatyor-21h16-336-m2',
      title: 'Арочный шатёр 21х16 — 336 м2',
      images: ['/1(3).webp' , '/3(oct).webp' , '/4.webp'],
      size: '21x16м',
      area: 336,
      availability: "да",
      basePrice: 1845000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-20h35',
      title: 'Шатёр для выставок 20х35',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '20x35м',
      area: 700,
      availability: "да",
      basePrice: 6593000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-20h30',
      title: 'Шатёр для мероприятий 20х30',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '20x35м',
      area: 600,
      availability: "да",
      basePrice: 5845000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-20h40',
      title: 'Шатёр для выставок 20х40',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '20x40м',
      area: 800,
      availability: "да",
      basePrice: 7370000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-meropriyatiy-20h40',
      title: 'Шатёр для мероприятий 20х40',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '20x40м',
      area: 800,
      availability: "да",
      basePrice: 7370000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-20h30',
      title: 'Шатёр для выставок 20х30',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '20x35м',
      area: 600,
      availability: "да",
      basePrice: 5845000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Прямоугольник"
    },
    {
      id: 'shatyor-dlya-vystavok-25h25',
      title: 'Шатёр для выставок 25х25',
      images: ['/15x25,1.webp', '/15x25,2.webp', '/15x25,3.webp'], 
      size: '25x25м',
      area: 625,
      availability: "да",
      basePrice: 5260000,
      discountPercentage: globalDiscount,
      price: "",
      shape: "Квадрат"
    },
    // ... add more products here
  ] as Omit<Product, 'capacity' | 'oldPrice' | 'discount' | 'price'>[]
).map((product): Product => {
  const calculated = calculateProductDetails(
    product.area,
    product.basePrice,
    product.discountPercentage
  );
  return {
    ...product,
    capacity: calculated.capacity,
    oldPrice: calculated.oldPrice,
    discount: calculated.discount,
    price: calculated.price,
  };
});

export default mockProducts;
